[workspace]
members = ["physics-integration-layer", "rapier2d", "rapier3d", "xpbd2d", "xpbd3d", "examples-crate"]

[package]
name = "bevy-tnua"
description = "A floating character controller for bevy_rapier"
version = "0.14.0"
edition = "2021"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/bevy-tnua"
documentation = "https://docs.rs/bevy-tnua"
readme = "README.md"
categories = ["game-development"]
keywords = ["bevy", "gamedev", "locomotion", "game-controls"]
exclude = [
    "assets",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "^0.12", default-features = false }
bevy-tnua-physics-integration-layer = { version = "0.1.0", path = "physics-integration-layer" }
thiserror = "1.0.53"

[dev-dependencies]
bevy = { version = "^0.12", default-features = false, features = [
     "animation",
    "bevy_asset",
    # "bevy_audio",
    "bevy_gilrs",
    # "bevy_scene",
    # "bevy_winit",
    "bevy_render",
    "bevy_gltf",
    "ktx2",
    "zstd",
    "tonemapping_luts",
    "bevy_text",
    # "png",
    # "hdr",
    # "vorbis",
    "x11",
    # "filesystem_watcher",
] }

[package.metadata.docs.rs]
all-features = true
