[package]
name = "bevy-tnua"
version = "0.1.0"
edition = "2021"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/bevy-tnua"
documentation = "https://docs.rs/bevy-tnua"
readme = "README.md"
categories = ["game-development"]
keywords = ["bevy", "gamedev", "locomotion", "game-controls"]
exclude = [
    "assets",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "^0.9", default-features = false }
bevy_rapier2d = { version = "^0.20", default-features = false, optional = true, features = ["dim2"]}
bevy_rapier3d = { version = "^0.20", default-features = false, optional = true, features = ["dim3"]}

[features]
rapier_2d = ["bevy_rapier2d"]
rapier_3d = ["bevy_rapier3d"]

[dev-dependencies]
bevy = { version = "^0.9", default-features = false, features = [
    # "animation",
    "bevy_asset",
    # "bevy_audio",
    "bevy_gilrs",
    # "bevy_scene",
    # "bevy_winit",
    "render",
    # "png",
    # "hdr",
    # "vorbis",
    "x11",
    # "filesystem_watcher",
] }
bevy_rapier2d = { version = "^0.20", features = ["debug-render-2d"]}
bevy_rapier3d = { version = "^0.20", features = ["debug-render"]}
bevy_egui = "0.19"
leafwing-input-manager = "0.8.0"

[[example]]
name = "platformer_2d"
required-features = ["rapier_2d"]

[[example]]
name = "platformer_3d"
required-features = ["rapier_3d"]
