[workspace]
members = ["physics-integration-layer", "rapier2d", "rapier3d", "xpbd2d", "xpbd3d"]

[package]
name = "bevy-tnua"
description = "A floating character controller for bevy_rapier"
version = "0.12.0"
edition = "2021"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/bevy-tnua"
documentation = "https://docs.rs/bevy-tnua"
readme = "README.md"
categories = ["game-development"]
keywords = ["bevy", "gamedev", "locomotion", "game-controls"]
exclude = [
    "assets",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "^0.12", default-features = false }
bevy-tnua-physics-integration-layer = { version = "0.1.0", path = "physics-integration-layer" }

[dev-dependencies]
bevy = { version = "^0.12", default-features = false, features = [
     "animation",
    "bevy_asset",
    # "bevy_audio",
    "bevy_gilrs",
    # "bevy_scene",
    # "bevy_winit",
    "bevy_render",
    "bevy_gltf",
    "ktx2",
    "zstd",
    "tonemapping_luts",
    "bevy_text",
    # "png",
    # "hdr",
    # "vorbis",
    "x11",
    # "filesystem_watcher",
] }

bevy_rapier2d = { version = "^0.23", features = ["debug-render-2d"]}
bevy-tnua-rapier2d = { version = "0.1.0", path = "rapier2d" }

bevy_rapier3d = { version = "^0.23", features = ["debug-render-3d"]}
bevy-tnua-rapier3d = { version = "0.1.0", path = "rapier3d" }

bevy_xpbd_2d = "^0.3"
bevy-tnua-xpbd2d = { version = "0.1.0", path = "xpbd2d" }

bevy_xpbd_3d = "^0.3"
bevy-tnua-xpbd3d = { version = "0.1.0", path = "xpbd3d" }

bevy_egui = "0.23"
egui_plot = "0.23"

[[example]]
name = "platformer_rapier2d"

[[example]]
name = "platformer_rapier3d"

[[example]]
name = "platformer_xpbd2d"

[[example]]
name = "platformer_xpbd3d"

[package.metadata.docs.rs]
all-features = true
