[package]
name = "bevy-tnua"
description = "A floating character controller for bevy_rapier"
version = "0.7.0"
edition = "2021"
authors = ["IdanArye <idanarye@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/idanarye/bevy-tnua"
documentation = "https://docs.rs/bevy-tnua"
readme = "README.md"
categories = ["game-development"]
keywords = ["bevy", "gamedev", "locomotion", "game-controls"]
exclude = [
    "assets",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "^0.10", default-features = false }
bevy_rapier2d = { version = "^0.21", default-features = false, optional = true, features = ["dim2"]}
bevy_rapier3d = { version = "^0.21", default-features = false, optional = true, features = ["dim3"]}

[features]
rapier_2d = ["bevy_rapier2d"]
rapier_3d = ["bevy_rapier3d"]

[dev-dependencies]
bevy = { version = "^0.10", default-features = false, features = [
     "animation",
    "bevy_asset",
    # "bevy_audio",
    "bevy_gilrs",
    # "bevy_scene",
    # "bevy_winit",
    "bevy_render",
    "bevy_gltf",
    "bevy_text",
    # "png",
    # "hdr",
    # "vorbis",
    "x11",
    # "filesystem_watcher",
] }
bevy_rapier2d = { version = "^0.21", features = ["debug-render-2d"]}
bevy_rapier3d = { version = "^0.21", features = ["debug-render"]}
bevy_egui = "0.20"
dolly = "0.4.2"

[[example]]
name = "platformer_2d"
required-features = ["rapier_2d"]

[[example]]
name = "platformer_3d"
required-features = ["rapier_3d"]

[package.metadata.docs.rs]

all-features = true
features = ["bevy_rapier2d/async-collider", "bevy_rapier3d/headless"]
